import { useState, useRef, useEffect } from 'react';
import api from '../api';
import './Playground.css';

export default function Playground() {
  const [messages, setMessages] = useState([
    { role: 'assistant', content: 'Hi! I\'m SolanaGPT, trained on TaoNet\'s decentralized network. Ask me anything about Solana, Anchor, Rust, or Web3 development.' }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [stats, setStats] = useState(null);
  const messagesRef = useRef(null);

  useEffect(() => {
    loadStats();
  }, []);

  useEffect(() => {
    if (messagesRef.current) {
      messagesRef.current.scrollTop = messagesRef.current.scrollHeight;
    }
  }, [messages]);

  async function loadStats() {
    const data = await api.getPlaygroundStats();
    if (data) setStats(data);
  }

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!input.trim() || loading) return;

    const userMessage = input.trim();
    setInput('');
    setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
    setLoading(true);

    try {
      const response = await api.queryPlayground(userMessage);
      if (response?.answer) {
        setMessages(prev => [...prev, { 
          role: 'assistant', 
          content: response.answer,
          source: response.source,
          miner: response.miner
        }]);
      } else {
        setMessages(prev => [...prev, { 
          role: 'assistant', 
          content: 'Sorry, no miners are available right now. Please try again later.',
          error: true
        }]);
      }
    } catch (err) {
      setMessages(prev => [...prev, { 
        role: 'assistant', 
        content: 'An error occurred. Please try again.',
        error: true
      }]);
    }

    setLoading(false);
    loadStats();
  };

  const examples = [
    'How do I create a Solana program with Anchor?',
    'Explain SPL tokens and how to create one',
    'What is the difference between PDAs and keypairs?',
    'How do I handle errors in Anchor programs?'
  ];

  return (
    <div className="page playground-page">
      <div className="playground-container">
        {/* Sidebar */}
        <div className="playground-sidebar">
          <div className="sidebar-header">
            <div className="model-badge">
              <div className="model-icon">T</div>
              <div>
                <span className="model-name">SolanaGPT</span>
                <span className="model-version">Powered by TaoNet</span>
              </div>
            </div>
          </div>

          <div className="sidebar-section">
            <h4>Specializations</h4>
            <div className="tags">
              <span className="tag">Solana</span>
              <span className="tag">Anchor</span>
              <span className="tag">Rust</span>
              <span className="tag">SPL Tokens</span>
              <span className="tag">NFTs</span>
              <span className="tag">DeFi</span>
            </div>
          </div>

          <div className="sidebar-section">
            <h4>Example Queries</h4>
            <div className="examples">
              {examples.map((ex, i) => (
                <button 
                  key={i} 
                  className="example-btn"
                  onClick={() => setInput(ex)}
                >
                  {ex}
                </button>
              ))}
            </div>
          </div>

          {stats && (
            <div className="sidebar-section">
              <h4>Network Stats</h4>
              <div className="sidebar-stats">
                <div className="sidebar-stat">
                  <span className="stat-value">{stats.knowledgeCount || 0}</span>
                  <span className="stat-label">Knowledge</span>
                </div>
                <div className="sidebar-stat">
                  <span className="stat-value">{stats.minersOnline || 0}</span>
                  <span className="stat-label">Miners</span>
                </div>
              </div>
            </div>
          )}

          <div className="sidebar-footer">
            <p>Responses are generated by decentralized miners on TaoNet network.</p>
          </div>
        </div>

        {/* Chat Area */}
        <div className="chat-area">
          <div className="chat-messages" ref={messagesRef}>
            {messages.map((msg, i) => (
              <div key={i} className={`message ${msg.role} ${msg.error ? 'error' : ''}`}>
                <div className="message-avatar">
                  {msg.role === 'assistant' ? 'T' : 'U'}
                </div>
                <div className="message-content">
                  <div className="message-text">{msg.content}</div>
                  {msg.source && (
                    <div className="message-meta">
                      <span>Source: {msg.source}</span>
                      {msg.miner && <span>Miner: {api.shortAddress(msg.miner)}</span>}
                    </div>
                  )}
                </div>
              </div>
            ))}
            {loading && (
              <div className="message assistant">
                <div className="message-avatar">T</div>
                <div className="message-content">
                  <div className="typing-indicator">
                    <span></span><span></span><span></span>
                  </div>
                </div>
              </div>
            )}
          </div>

          <form className="chat-input-form" onSubmit={handleSubmit}>
            <div className="chat-input-wrapper">
              <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask about Solana development..."
                disabled={loading}
              />
              <button type="submit" disabled={!input.trim() || loading}>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M22 2L11 13M22 2l-7 20-4-9-9-4 20-7z"/>
                </svg>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
